# The URL the site will be built for
base_url = "https://planchon.dev"

default_language = "en"

generate_feed = true
feed_filename = "rss.xml"

compile_sass = true
highlight_code = true
highlight_theme = "axar"
build_search_index = true

theme = "zerm"

[extra]
author = "you!"
show_author = false
show_categories = true
show_tags = true
theme_color = "green"
show_menu_items = 2
full_width = false
center = true
logo_text = "johan"
logo_home_link = "/"
main_menu = [
  {url="/about/", name="about"},
  {url="/contact/", name="contact"},
]
menu_more = "show more"
read_more = "read more"
read_other_posts = "read other posts"

