---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: template
  label: Templates
  create: all
  match: "**/*"
- type: heading
  label: Posts
- type: directory
  path: content/en
  label: Anglais
  create: all
  match: "**/*"
- type: directory
  path: content/fr
  label: Français
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: thibaultmorin/zola:latest
  mount_path: "/workdir"
  instant_preview_command: serve --interface 0.0.0.0 --port 8080 --output-dir public
