---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Anglais
- type: heading
  label: Français
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  preview_docker_image: thibaultmorin/zola:latest
  mount_path: "/workdir"
  instant_preview_command: serve --interface 0.0.0.0 --port 8080 --output-dir public
